name: Test Python app

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test-requirements.txt
    - name: Lint with flake8
      run: |
        flake8 app
    - name: Test with coverage
      run: |
        coverage run -m unittest
    - name: Test coverage report
      run: |
        coverage report
